// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TaskSharpHTTP.Models;

namespace ProyectoMorenita.Migrations
{
    [DbContext(typeof(AbacheContext))]
    [Migration("20191106220200_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("TaskSharpHTTP.Models.CategoriaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Imagen");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("CategoriaItems");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.PersonaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Apodo");

                    b.Property<string>("Direccion");

                    b.Property<string>("Email");

                    b.Property<string>("Identificacion");

                    b.Property<string>("Nombre");

                    b.Property<string>("Password");

                    b.Property<string>("Telefono");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("PersonaItems");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria");

                    b.Property<string>("Descripcion");

                    b.Property<byte[]>("Imagen");

                    b.Property<int>("Precio");

                    b.Property<string>("Subgrupo");

                    b.Property<string>("Tipo");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.ToTable("ProductItems");
                });
#pragma warning restore 612, 618
        }
    }
}
