// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TaskSharpHTTP.Models;

namespace ProyectoMorenita.Migrations
{
    [DbContext(typeof(AbacheContext))]
    [Migration("20191121163423_CxAbache")]
    partial class CxAbache
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("TaskSharpHTTP.Models.CarroItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cantidad");

                    b.Property<int>("Id_cliente");

                    b.Property<int>("Id_producto");

                    b.HasKey("Id");

                    b.ToTable("CarroItems");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.CategoriaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<byte[]>("Imagen")
                        .HasColumnName("IMAGEN");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id");

                    b.ToTable("CategoriaItems");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.CiudadItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CIUDAD");

                    b.Property<int?>("ID_DEPARTAMENTO");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id");

                    b.HasIndex("ID_DEPARTAMENTO");

                    b.ToTable("CiudadItem");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.DepartamentoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_DEPARTAMENTO");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id");

                    b.ToTable("DepartamentoItem");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.EtiquetaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_ETIQUETA");

                    b.Property<int?>("ID_CATEGORIA");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id");

                    b.HasIndex("ID_CATEGORIA");

                    b.ToTable("EtiquetaItems");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.PersonaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PERSONA");

                    b.Property<string>("Apellido")
                        .HasColumnName("APELLIDOS");

                    b.Property<string>("Apodo")
                        .HasColumnName("APODO");

                    b.Property<string>("Direccion")
                        .HasColumnName("DIRECCION");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("ID_CIUDAD");

                    b.Property<int?>("ID_DEPARTAMENTO");

                    b.Property<int?>("ID_ROL");

                    b.Property<byte[]>("Imagen")
                        .HasColumnName("IMAGEN");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRES");

                    b.Property<string>("Password")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Telefono")
                        .HasColumnName("TELEFONO");

                    b.HasKey("Id");

                    b.HasIndex("ID_CIUDAD");

                    b.HasIndex("ID_DEPARTAMENTO");

                    b.HasIndex("ID_ROL");

                    b.ToTable("PersonaItems");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<int>("Cantidad")
                        .HasColumnName("CANTIDAD");

                    b.Property<string>("Descripcion")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("Estilo_color")
                        .HasColumnName("ESTILO_COLOR");

                    b.Property<int?>("ID_CATEGORIA");

                    b.Property<int?>("ID_ETIQUETA");

                    b.Property<int?>("ID_PERSONA");

                    b.Property<byte[]>("Imagen")
                        .HasColumnName("IMAGEN");

                    b.Property<int>("Precio")
                        .HasColumnName("PRECIO");

                    b.Property<string>("Titulo")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("ID_CATEGORIA");

                    b.HasIndex("ID_ETIQUETA");

                    b.HasIndex("ID_PERSONA");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.RolItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_ROL");

                    b.Property<string>("Gestion_usuarios")
                        .HasColumnName("GESTION_USUARIOS");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Permiso_compra")
                        .HasColumnName("PERMISO_COMPRA");

                    b.Property<string>("Permiso_venta")
                        .HasColumnName("PERMISO_VENTA");

                    b.HasKey("Id");

                    b.ToTable("RolItem");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.CiudadItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.DepartamentoItem", "Id_departamento")
                        .WithMany()
                        .HasForeignKey("ID_DEPARTAMENTO");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.EtiquetaItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.CategoriaItem", "Id_categoria")
                        .WithMany()
                        .HasForeignKey("ID_CATEGORIA");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.PersonaItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.CiudadItem", "Id_ciudad")
                        .WithMany()
                        .HasForeignKey("ID_CIUDAD");

                    b.HasOne("TaskSharpHTTP.Models.DepartamentoItem", "Id_departamento")
                        .WithMany()
                        .HasForeignKey("ID_DEPARTAMENTO");

                    b.HasOne("TaskSharpHTTP.Models.RolItem", "Id_rol")
                        .WithMany()
                        .HasForeignKey("ID_ROL");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.ProductItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.CategoriaItem", "Id_categoria")
                        .WithMany()
                        .HasForeignKey("ID_CATEGORIA");

                    b.HasOne("TaskSharpHTTP.Models.EtiquetaItem", "Id_etiqueta")
                        .WithMany()
                        .HasForeignKey("ID_ETIQUETA");

                    b.HasOne("TaskSharpHTTP.Models.PersonaItem", "Id_proveedor")
                        .WithMany()
                        .HasForeignKey("ID_PERSONA");
                });
#pragma warning restore 612, 618
        }
    }
}
