// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TaskSharpHTTP.Models;

namespace ProyectoMorenita.Migrations
{
    [DbContext(typeof(AbacheContext))]
    partial class AbacheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("TaskSharpHTTP.Models.CarroItem", b =>
                {
                    b.Property<int>("Id_carro")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CARRO");

                    b.Property<int>("Cantidad")
                        .HasColumnName("CANTIDAD")
                        .HasColumnType("Number(3)");

                    b.Property<string>("Estado")
                        .HasColumnName("ESTADO")
                        .HasColumnType("varchar2(30)");

                    b.Property<int>("Id_persona")
                        .HasColumnName("ID_PERSONA");

                    b.Property<int>("Id_producto")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<int>("Total")
                        .HasColumnName("TOTAL");

                    b.HasKey("Id_carro");

                    b.HasIndex("Id_persona");

                    b.HasIndex("Id_producto");

                    b.ToTable("CARROITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.CategoriaItem", b =>
                {
                    b.Property<int>("Id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id_categoria");

                    b.ToTable("CATEGORIAITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.CiudadItem", b =>
                {
                    b.Property<int>("Id_ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CIUDAD");

                    b.Property<int>("Id_departamento")
                        .HasColumnName("ID_DEPARTAMENTO");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(10)");

                    b.HasKey("Id_ciudad");

                    b.HasIndex("Id_departamento");

                    b.ToTable("CIUDADITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.DepartamentoItem", b =>
                {
                    b.Property<int>("Id_departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_DEPARTAMENTO");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(10)");

                    b.HasKey("Id_departamento");

                    b.ToTable("DEPARTAMENTOITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.EtiquetaItem", b =>
                {
                    b.Property<int>("Id_etiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_ETIQUETA");

                    b.Property<int>("Id_categoria")
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id_etiqueta");

                    b.HasIndex("Id_categoria");

                    b.ToTable("ETIQUETAITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.FacturaDetalleItem", b =>
                {
                    b.Property<int>("Id_facturadetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_FACTURADETALLE");

                    b.Property<int>("Cantidad")
                        .HasColumnName("CANTIDAD")
                        .HasColumnType("NUMBER(4)");

                    b.Property<string>("Estilo_color")
                        .HasColumnName("ESTILO_COLOR")
                        .HasColumnType("VARCHAR2(15)");

                    b.Property<int>("Id_factura")
                        .HasColumnName("ID_FACTURA");

                    b.Property<int>("Id_producto")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<int>("Id_vendedor")
                        .HasColumnName("ID_VENDEDOR");

                    b.Property<int>("Precio")
                        .HasColumnName("PRECIO");

                    b.Property<string>("Titulo")
                        .HasColumnName("TITULO")
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<int>("Total_producto")
                        .HasColumnName("TOTAL_PRODUCTO");

                    b.HasKey("Id_facturadetalle");

                    b.HasIndex("Id_factura");

                    b.ToTable("FACTURADETALLEITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.FacturaItem", b =>
                {
                    b.Property<int>("Id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_FACTURA");

                    b.Property<string>("Apellido")
                        .HasColumnName("APELLIDO_PERSONA")
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("Direccion")
                        .HasColumnName("DIRECCION")
                        .HasColumnType("VARCHAR2(15)");

                    b.Property<int>("Id_persona")
                        .HasColumnName("ID_PERSONA");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE_PERSONA")
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("Telefono")
                        .HasColumnName("TELEFONO")
                        .HasColumnType("VARCHAR2(10)");

                    b.Property<string>("ciudad")
                        .HasColumnName("CIUDAD")
                        .HasColumnType("VARCHAR2(10)");

                    b.Property<string>("departamento")
                        .HasColumnName("DEPARTAMENTO")
                        .HasColumnType("VARCHAR2(10)");

                    b.Property<DateTime>("fecha")
                        .HasColumnName("FECHA");

                    b.HasKey("Id_factura");

                    b.HasIndex("Id_persona");

                    b.ToTable("FACTURAITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.PersonaItem", b =>
                {
                    b.Property<int>("Id_persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PERSONA");

                    b.Property<string>("Apellido")
                        .HasColumnName("APELLIDOS")
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("Apodo")
                        .HasColumnName("APODO")
                        .HasColumnType("VARCHAR2(10)");

                    b.Property<string>("Direccion")
                        .HasColumnName("DIRECCION")
                        .HasColumnType("VARCHAR2(15)");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<int>("Id_ciudad")
                        .HasColumnName("ID_CIUDAD");

                    b.Property<int>("Id_departamento")
                        .HasColumnName("ID_DEPARTAMENTO");

                    b.Property<int>("Id_rol")
                        .HasColumnName("ID_ROL");

                    b.Property<byte[]>("Imagen")
                        .HasColumnName("IMAGEN");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRES")
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("Password")
                        .HasColumnName("PASSWORD")
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<string>("Telefono")
                        .HasColumnName("TELEFONO")
                        .HasColumnType("VARCHAR2(10)");

                    b.HasKey("Id_persona");

                    b.HasIndex("Id_ciudad");

                    b.HasIndex("Id_departamento");

                    b.HasIndex("Id_rol");

                    b.ToTable("PERSONAITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.ProductItem", b =>
                {
                    b.Property<int>("Id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<string>("Descripcion")
                        .HasColumnName("DESCRIPCION")
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<string>("Estilo_color")
                        .HasColumnName("ESTILO_COLOR")
                        .HasColumnType("VARCHAR2(15)");

                    b.Property<int>("Id_persona")
                        .HasColumnName("ID_VENDEDOR");

                    b.Property<int>("Inventario")
                        .HasColumnName("INVENTARIO");

                    b.Property<int>("Precio")
                        .HasColumnName("PRECIO");

                    b.Property<string>("Titulo")
                        .HasColumnName("TITULO")
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("Id_producto");

                    b.HasIndex("Id_persona");

                    b.ToTable("PRODUCTITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.RolItem", b =>
                {
                    b.Property<int>("Id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_ROL");

                    b.Property<string>("Nombre")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id_rol");

                    b.ToTable("ROLITEM");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.CarroItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.PersonaItem", "PersonaItem")
                        .WithMany("CarroItems")
                        .HasForeignKey("Id_persona")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskSharpHTTP.Models.ProductItem", "ProductItem")
                        .WithMany("CarroItems")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.CiudadItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.DepartamentoItem", "departamentoItem")
                        .WithMany("CiudadItems")
                        .HasForeignKey("Id_departamento")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.EtiquetaItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.CategoriaItem", "categoriaItem")
                        .WithMany("EtiquetaItems")
                        .HasForeignKey("Id_categoria")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.FacturaDetalleItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.FacturaItem", "facturaItem")
                        .WithMany("FacturaDetalleItems")
                        .HasForeignKey("Id_factura")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.FacturaItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.PersonaItem", "PersonaItem")
                        .WithMany("FacturaItems")
                        .HasForeignKey("Id_persona")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.PersonaItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.CiudadItem", "ciudadItem")
                        .WithMany("PersonaItems")
                        .HasForeignKey("Id_ciudad")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskSharpHTTP.Models.DepartamentoItem", "departamentoItem")
                        .WithMany("PersonaItems")
                        .HasForeignKey("Id_departamento")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskSharpHTTP.Models.RolItem", "rolItem")
                        .WithMany("PersonaItems")
                        .HasForeignKey("Id_rol")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.ProductItem", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.PersonaItem", "PersonaItem")
                        .WithMany("ProductItems")
                        .HasForeignKey("Id_persona")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
